[package]
name = "egui-rust-wgpu-hello"
version = "1.0.0"
edition = "2021"

[dependencies]
egui = "0.31.1"
egui-wgpu = { version = "0.31.1",features = ["winit"] }
egui-winit = "0.31.1"
winit = "0.30.9"
pollster = "0.4.0"
egui_material_icons = "0.3.0"
pulldown-cmark = "0.13.0"
egui_commonmark = { version = "0.20.0", features = [
    "better_syntax_highlighting",
    "svg",
    "fetch",
    "embedded_image",
]}
reqwest = { version = "0.12.22", features = ["blocking"] }
image = { version = "0.25", default-features = false, features = [
    "jpeg",  # JPEG support
    "png",   # PNG support
    "gif",   # GIF support
    "webp",  # WebP support
    "tiff",  # TIFF support
]}

anyhow = "1.0.98"
futures = "0.3.31"
clap = { version = "4.5.41", features = ["derive"] }
wasi-frame-buffer-wasmtime = { path = "wasi-gfx-runtime/crates/wasi-frame-buffer-wasmtime"}
wasi-graphics-context-wasmtime = { path = "wasi-gfx-runtime/crates/wasi-graphics-context-wasmtime"}
wasi-webgpu-wasmtime = { path = "wasi-gfx-runtime/crates/wasi-webgpu-wasmtime"}
wasi-surface-wasmtime = { path = "wasi-gfx-runtime/crates/wasi-surface-wasmtime", features = ["winit"] }
wasmtime = { version = "31.0", features = ['component-model'] }
wasmtime-wasi = "31.0"
wgpu-core = "24"
wgpu-types = "24"
tokio = { version = "1.44", features = ["full"] }
